### ISSUE TITLE
Does this action officially support BuildKit?

### ISSUE THREAD

**Issue by inductor** [docker/github-actions#12]
I assume it supports BuildKit by using ENV like you do in your GitHub Actions YAML https://github.com/docker/github-actions/blob/826b584752ffa6abc1a2d94da26f348e3e4f73d0/.github/workflows/main.yml#L27

Based on this I can see this builder is based on the Docker builder but there's no documentation for it.

Does this action officially support BuildKit?

**Comment by justincormack** [comment]
Yes, we do support BuildKit. We are looking to support the `buildx` extensions as well.

**Comment by olegburov** [comment]
Why not enable BuildKit by default. So that users who don't know about BuildKit can also benefit of speedy builds.

**Comment by crazy-max** [comment]
I have created an [action to setup buildx](https://github.com/crazy-max/ghaction-docker-buildx) if you want to take a look.

**Comment by bhack** [comment]
I have a related ticket about `action/cache` with the BuildKit cache mount at https://github.com/actions/cache/issues/260

**Comment by jonpulsifer** [comment]
I understand BuildKit is ubiquitous to some, but it was not clear to us that GitHub Actions supported it today such that we lost some time.

Could this be documented better somehow? [Here](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) maybe?

**Comment by shrespect0413** [comment]
Https://btcoinpromo.cash
Invest BitCoin & profits (USD)
Invest Plans:
Bronze ($100 min)($5000 max) 7% Per 1Hour
Silver ($1010 min)($50000 max) 13% Per 1Day
Gold ($10010 min)($100000 max) 33% Per 1Week
Platinum ($15010 min)($150000 max) 40% Per 1Month
Diamond ($25010 min)($500000 max) 70% Per 1Year

**Comment by kurt-mueller-osumc** [comment]
> Specifically we were wanting to use the [build secrets](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information) but that was not easy and we gave up 😄

Hey @jonpulsifer, did you ever figure this out?

Thanks for any info.

**Comment by chris-crone** [comment]
This action is now deprecated. Please take a look at the [upgrade notes](https://github.com/docker/build-push-action/blob/master/UPGRADE.md) to move to the build-push action.
