### ISSUE TITLE
Typo in news?

### ISSUE THREAD

**Issue by Jeckerson** [docker/github-actions#13]
Hi

Question: Do you use same credential for both?
https://www.docker.com/blog/first-docker-github-action-is-here/

![image](https://user-images.githubusercontent.com/3289702/76939178-d77d3180-68ef-11ea-93bd-d3836f49dbab.png)

Cheers

**Comment by zappy-shu** [comment]
Hi @Jeckerson thanks for pointing this out. I've sent out a correction.

It should read as you'd expect:

```
username: ${{ DOCKER_USERNAME }}
password: ${{ DOCKER_PASSWORD }}
```

The correction should be on the blog ASAP
