### ISSUE TITLE
Support for Outputs

### ISSUE THREAD

**Issue by andrew-waters** [docker/github-actions#18]
Thanks for the work on this. Are there any plans to add outputs to the action?

Before diving in to a PR, I wanted to see if it was being worked on or whether there are valid reasons not to add support.

Info: https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

**Comment by compliancedb** [comment]
I would love to see this.  It would be very helpful to get the repo digest and image name in following steps.  Let me know if I can contribute!

**Comment by tonistiigi** [comment]
Some outputs are defined in https://github.com/docker/build-push-action/issues/71 . Comment on that issue if you need more.
