### ISSUE TITLE
Failing builds with = character in branch name 

### ISSUE THREAD

**Issue by jebw** [docker/github-actions#19]
If there is an equals symbol in the branch name, the `build-push-action` fails to build with

```
Building image [myorg/myrepo:initial-home=page-tweaks myorg/myrepo:sha-5d13f16]
invalid argument "myorg/myrepo:initial-home=page-tweaks" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Error: exit status 125
Usage:
exit status 125
  github-actions build-push [flags]
Flags:
  -h, --help   help for build-push
```

Should there be some special casing for this inline with how there's special casing for slashes in branch names?

Thanks

**Comment by tonistiigi** [comment]
References grammar is defined in https://github.com/docker/distribution/blob/master/reference/reference.go#L4
