### ISSUE TITLE
Handle credentials securely

### ISSUE THREAD

**Issue by eine** [docker/github-actions#21]
As other Actions by GitHub or Microsoft, the one using this codebase seems to not handle credentials securely: https://github.com/docker/github-actions/runs/609042636?check_suite_focus=true#step:5:18. It would be desirable to have an official action which handles login properly.

Refs actions/starter-workflows#96 docker/build-push-action#53

**Comment by tonistiigi** [comment]
lets track this in docker/build-push-action#53 . The warning is for the cli usage in the shell. With the current auth methods and the way actions handle secrets only change we can do is make sure login clears after action completes.
