### ISSUE TITLE
Is the docker image available/valid?

### ISSUE THREAD

**Issue by umarcor** [docker/github-actions#22]
I tried to login using this Action, as explained in the README (https://github.com/docker/github-actions#commands):

```yml
  - run: |
      docker pull docker/github-actions
      INPUT_USERNAME="umarcor" INPUT_PASSWORD="${{ secrets.GITHUB_TOKEN }}" INPUT_REGISTRY="docker.pkg.github.com" docker run docker/github-actions login
```

But the image seems not to exist:

```sh
# docker pull docker/github-actions
Using default tag: latest
Error response from daemon: manifest for docker/github-actions:latest not found: manifest unknown: manifest unknown
```

**Comment by tonistiigi** [comment]
`docker/github-actions:v1`

**Comment by umarcor** [comment]
@tonistiigi, thanks. I tried with `docker/github-actions:v1`, but I get:

```
Logging in to registry 
Error: Cannot perform an interactive login from a non TTY device
Error: exit status 1
Usage:
  github-actions login [flags]

Flags:
  -h, --help   help for login

exit status 1
```

It I use `-it`, instead of `-t`, the error is the following: `the input device is not a TTY`.

**Comment by chris-crone** [comment]
This action is now deprecated. Please take a look at the [upgrade notes](https://github.com/docker/build-push-action/blob/master/UPGRADE.md) to move to the build-push action.
