### ISSUE TITLE
Optional output of full image tag

### ISSUE THREAD

**Issue by kyler-hyuna** [docker/github-actions#24]
I see that https://github.com/docker/build-push-action uses this as the base for its commands.

I'm always looking for ways to reduce boilerplate in my github actions. In this case the full image URL. There's an [open issue](https://github.com/docker/build-push-action/issues/24) for having this as an output. 

So given the conditions:
Trigger is push/tag. Say `1.4`.  And the repo being hello-world. The output generated for the below:

```
username: ${{ github.actor }}
password: ${{ github.token }}
registry: docker.pkg.github.com
repository: ${{ github.repository }}/hello-world
tag_with_ref: true
```

Should be able to get a full URL to the image:

```
docker.pkg.github.com/kyler-hyuna/hello-world/hello-world:1.4
```

**Comment by chris-crone** [comment]
This action is now deprecated. Please take a look at the [upgrade notes](https://github.com/docker/build-push-action/blob/master/UPGRADE.md) to move to the build-push action.
