### ISSUE TITLE
feature/doc run

### ISSUE THREAD

**Issue by xenoterracide** [docker/github-actions#26]
I don't see how you can use docker run in the readme, would be great to have a docker run that took `env:` and `volumes` and stuff. I need to use docker run because I'm using buildkit, and an exception is being thrown in docker compose.

**Comment by chris-crone** [comment]
This action is now deprecated. Please take a look at the [upgrade notes](https://github.com/docker/build-push-action/blob/master/UPGRADE.md) to move to the build-push action.
